### ISSUE TITLE
Field name should better represent content

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-elasticsearch#3]
https://github.com/openskope/skope-elasticsearch/blob/bf72faa8494eecafc767a3243b822cff2eef09ed/skope.search.mapping.json#L43

I think the previous name `geometry` is better than the current `geojson`. The stuff you store inside it is actually the `geometry` field of a GeoJSON `Feature`.

**Comment by jterstriep** [comment]
Ok, let's standardize on region.geometry which will contain a geojson geometry fragment. The field definition spreadsheet has been updated and the next build of the staging server will have this change.
